### PR TITLE
feat(centos): epel is not hard requirement for pip

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)
- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---
#### Primary type
- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type
- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

The `epel` state is required by default, but it's not actually needed. 

### Debug log showing how the proposed changes work

Here is unnecessary failures - python2-pip is already installed so epel is not a hard requirement.
```
          ID: pip_req_pkgs
    Function: pkg.installed
      Result: True
     Comment: 2 targeted packages were installed/updated.
              The following packages were already installed: gcc
     Started: 10:53:20.147587
    Duration: 19811.277 ms
     Changes:
              ----------
              python-backports:
                  ----------
                  new:
                      1.0-8.el7
                  old:
              python-backports-ssl_match_hostname:
                  ----------
                  new:
                      3.5.0.1-1.el7
                  old:
              python-devel:
                  ----------
                  new:
                      2.7.5-86.el7
                  old:
              python-ipaddress:
                  ----------
                  new:
                      1.0.16-2.el7
                  old:
              python-rpm-macros:
                  ----------
                  new:
                      3-32.el7
                  old:
              python-setuptools:
                  ----------
                  new:
                      0.9.8-7.el7
                  old:
              python2-pip:
                  ----------
                  new:
                      8.1.2-10.el7
                  old:
              python2-rpm-macros:
                  ----------
                  new:
                      3-32.el7
                  old:
----------
          ID: packages pips install tox
    Function: pip.installed
        Name: tox
      Result: False
     Comment: One or more requisite failed: epel.set_gpg_epel, epel.epel_release, epel.set_pubkey_epel
     Started: 10:53:45.701745
    Duration: 0.006 ms
     Changes:
----------
          ID: packages pips install click
    Function: pip.installed
        Name: click
      Result: False
     Comment: One or more requisite failed: epel.set_gpg_epel, epel.epel_release, epel.set_pubkey_epel
     Started: 10:53:45.702434
    Duration: 0.002 ms
     Changes:
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@noelmcloughlin Please look at the `yamllint` errors introduced here:

* https://travis-ci.com/saltstack-formulas/packages-formula/jobs/280252500#L306-L317

**Comment by noelmcloughlin** [comment]
lint is fixed now. thanks.

**Comment by myii** [comment]
@noelmcloughlin Thanks for fixing things up.  The failures are unrelated to this PR and I've prepared a fix to put on top of this PR, which I'll try to push soon:

* https://cirrus-ci.com/build/5714295791026176

**Comment by myii** [comment]
@noelmcloughlin Had to force push to minimise the changes since this PR was first proposed.  `kitchen.yml` would have been a lot of work to fix manually.

**Comment by noelmcloughlin** [comment]
> @noelmcloughlin Had to force push to minimise the changes since this PR was first proposed. `kitchen.yml` would have been a lot of work to fix manually.

Thanks @myii no bother. tests are passing.

**Comment by myii** [comment]
> Thanks @myii no bother. tests are passing.

That was _after_ I pushed the commits.  We recently changed the pre-salted images so Debian and Ubuntu were failing here, after you got the lint working.

**Pull request merged**
