### PR TITLE
fix(rhel): redhat enterprise 8 use dnf, not yum

### PR DESCRIPTION
**Pull request by Yoda-BZH**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

https://github.com/saltstack-formulas/packages-formula/pull/72#issuecomment-913648936

### Describe the changes you're proposing

Redhat Enterprise switch from yum to dnf in version 8

### Debug log showing how the proposed changes work

```
local:
----------
          ID: pkg_req_pkgs
    Function: pkg.installed
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "The following packages failed to install/update: yum-plugin-versionlock"
              Attempt 2: Returned a result of "False", with the following comment: "The following packages failed to install/update: yum-plugin-versionlock"
              The following packages failed to install/update: yum-plugin-versionlock
     Started: 15:15:05.139721
    Duration: 154690.206 ms
     Changes:   
----------
          ID: wanted_pkgs
    Function: pkg.installed
      Result: False
     Comment: One or more requisite failed: packages.pkgs.pkg_req_pkgs
     Started: 15:17:39.955091
    Duration: 0.002 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    2
------------
root@server:~# salt-call grains.get osfingermap
local:

root@server:~# salt-call grains.get osfinger
local:
    Red Hat Enterprise Linux-8

root@server:~# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.4 (Ootpa)

```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by Yoda-BZH** [comment]
I have some troubles with the CI jobs. The errors doesn't seems to be related to my changes.

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
> I have some troubles with the CI jobs. The errors doesn't seems to be related to my changes.

@Yoda-BZH Yes, we've got a few problems because this formula relies on the `node-formula`, as we discussed there.  We can get this all fixed in due course.

Thanks for the PR!

**Comment by myii** [comment]
@Yoda-BZH Out of interest, how do you install Salt on RHEL-8?  As I mentioned in https://github.com/saltstack-formulas/packages-formula/pull/72#issuecomment-913653058, I'm pretty sure it can't be installed by the `salt-bootstrap`.

If the instructions are simple enough, perhaps we can add it to our `salt-image-builder`, so that we can provide pre-salted images of RHEL-8 (and maybe even RHEL-7), which can be added to our testing across formulas.

**Comment by myii** [comment]
> If the instructions are simple enough, perhaps we can add it to our `salt-image-builder`, so that we can provide pre-salted images of RHEL-8 (and maybe even RHEL-7), which can be added to our testing across formulas.

@Yoda-BZH I realised that I had tried this before and it wasn't installing Salt that was the problem.

```console
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
```

This results in certain packages not being able to be installed, such as `openssh-server` -- without that, Test Kitchen isn't going to work.

**Comment by Yoda-BZH** [comment]
@myii yeah we're using a redhat satellite at $work. I don't know if a RHEL can work without it :s

**Pull request merged**
